kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: {{ include "ecr-pull-through.fullname" . }}
  labels:
    {{- include "ecr-pull-through.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "ecr-pull-through.fullname" . }}
webhooks:
  - name: {{ include "ecr-pull-through.fullname" . }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "ecr-pull-through.fullname" . }}
        path: /mutate
        port: {{ .Values.service.port }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    {{- with .Values.WebhookNamespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    sideEffects: None
    admissionReviewVersions: ["v1"]